### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by rahlk** [CSC591-MASE/x9115YSS#12]
Your neighbor function is incorrect. In [Line 78](https://github.com/CSC591-MASE/x9115YSS/blob/master/hw/code/4/Schaffer.py#L78), you call the neighbor function. And in [Line 
15](https://github.com/CSC591-MASE/x9115YSS/blob/master/hw/code/4/Schaffer.py#L15), you use `random.random()`. Note that `random.random()` only generates values between 0 and 1. We need values between x_min and x_max. I'd rather you use `random.uniform(x_min,x_max)`. 

Or, you may also use the current soultion to generate it's neighbor. For instance,
``` python
def neigh(x,xmax=1e-5,xmin=1e+5):
  rad = min(x-xmin, xmax-x)
  return random.uniform(x-rad,x+rad)
```

**Comment by shubham90** [comment]
Thanks for pointing this out @rahlk. I will change the solution accordingly.

**Comment by shubham90** [comment]
@rahlk I have updated the submission to include the range function. Please let me know if this is ok or requires more changes.

**Comment by shubham90** [comment]
Link : https://github.com/CSC591-MASE/x9115YSS/tree/master/hw/code/4

**Comment by rahlk** [comment]
Hey, 
Pardon me for the delayed response. This seems ok, but in [line 57](https://github.com/CSC591-MASE/x9115YSS/blob/master/hw/code/4/Schaffer.py#L57) you're still using the same random.random() as choice. You'll need to change that too..

**Comment by rahlk** [comment]
The rest seems ok, so i'll grade you for this.

**Comment by shubham90** [comment]
@rahlk Thanks for pointing that. I am sorry that I missed that! I have changed it now. Thanks again.
